Repository FRONT-END-BOOTCAMP-PLUS-3/Rolly, pull requests merged in 2025-02, with the labels that each got.

#8 ✨ feat: 만든/받은 롤리 목록 구현
  components/rollyList/RollyListItem.module.scss
  components/rollyList/RollyListItem.tsx
  public/icons/delete.svg
  public/icons/lock.svg
  public/icons/reply.svg
Labels: ✨ feature, 💄 style

#12 ✨ feat: Alert 컴포넌트 구현
  components/alert/Alert.module.scss
  components/alert/Alert.tsx
Labels: ✨ feature, 💄 style

#16 ✨ feat: 만든 롤리함 페이지 구현
  app/api/rollies/route.ts
  app/member/rollies/created/page.tsx
  application/usecases/rolly/DfCreatedRollyUsecase.ts
  application/usecases/rolly/dto/CreatedRollyDto.ts
  components/rollyItem/RollyItem.module.scss
  components/rollyItem/RollyItem.tsx
  domain/repositories/CreatedRollyRepository.ts
  domain/repositories/RollyRepository.ts
  infrastructure/repositories/SbCreatedRollyRepository.ts
  infrastructure/repositories/SbRollyRepository.ts
Labels: ✨ feature

#18 ✨ feat: 클린 아키텍처 기반 Rolly 테마 목록, 포스트잇 테마 목록, 폰트 목록 조회 구현
  app/api/fontfamilies/route.ts
  app/api/postitthemes/route.ts
  app/api/rollythemes/route.ts
  application/usecases/fontFamily/DfFontFamilyListUsecase.ts
  application/usecases/fontFamily/dto/FontFamilyListDto.ts
  application/usecases/postitTheme/DfPostitThemeListUsecase.ts
  application/usecases/postitTheme/dto/PostitThemeListDto.ts
  application/usecases/rollyTheme/DfRollyThemeListUsecase.ts
  application/usecases/rollyTheme/dto/RollyThemeListDto.ts
  domain/entities/FontFamily.ts
  domain/entities/PostitTheme.ts
  domain/entities/RollyBgTheme.ts
  domain/entities/RollyTheme.ts
  domain/repositories/FontFamilyRepository.ts
  domain/repositories/PostitThemeRepository.ts
  domain/repositories/RollyBgThemeRepository.ts
  domain/repositories/RollyThemeRepository.ts
  infrastructure/repositories/SbFontFamilyRepository.ts
  infrastructure/repositories/SbPostitThemeRepository.ts
  infrastructure/repositories/SbRollyBgThemeRepository.ts
  infrastructure/repositories/SbRollyThemeRepository.ts
Labels: ✨ feature

#19 ✨ feat: 롤리 페이지 구현
  app/api/postits/route.ts
  app/api/rollies/[id]/route.ts
  app/global.scss
  app/member/rollies/[id]/page.tsx
  application/state/useRollyStore.ts
  application/usecases/postit/DfPostitsUsecase.ts
  application/usecases/postit/dto/PostitDto.ts
  application/usecases/rolly/DfRollyDetailUsecase.ts
  application/usecases/rolly/dto/RollyDetailDto.ts
  components/rolly/Rolly.module.scss
  components/rolly/Rolly.tsx
  components/rolly/Rolly.type.ts
  domain/repositories/PostitRepository.ts
  domain/repositories/RollyRepository.ts
  infrastructure/repositories/SbPostitRepository.ts
  infrastructure/repositories/SbRollyRepository.ts
  next.config.ts
Labels: ✨ feature, 💄 style, 🦄 API

#21 ✨ feat: member 루트 페이지 구현
  app/api/users/route.ts
  app/member/page.module.scss
  app/member/page.tsx
  application/usecases/user/DfUserNameUsecase.ts
  application/usecases/user/dto/UserNameDto.ts
  components/createRollyButton/CreateRollyButton.tsx
  components/modal/Modal.module.scss
  domain/entities/User.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/SbUserRepository.ts
  public/images/mascot.svg
Labels: ✨ feature, 💄 style, 🦄 API

#26 ♻️ refactor: 롤리 만들기 페이지 리팩토링
  app/(anon)/postits/create/page.tsx
  app/api/images/route.ts
  app/api/rollies/route.ts
  app/member/page.tsx
  app/member/postits/create/page.tsx
  app/member/rollies/create/page.tsx
  application/usecases/rolly/DfUploadImageUsecase.ts
  components/modal/Modal.tsx
  components/modal/Modal.type.ts
  domain/repositories/ImageRepository.ts
  infrastructure/repositories/SbImageRepository.ts
Labels: ♻️ refactor

#27 ✨ feat: 로그아웃 기능 추가
  app/member/page.tsx
Labels: ✨ feature

#28 ✨ feat: anon 루트 페이지 구현
  app/(anon)/page.module.scss
  app/(anon)/page.tsx
  app/auth/callback/route.ts
  app/auth/page.module.scss
  app/auth/page.tsx
  components/loading/Loading.module.scss
  components/loading/Loading.tsx
  public/icons/google.svg
  public/icons/kakao.svg
  public/images/main.svg
  public/images/mascot.svg
Labels: ✨ feature, 💄 style, 🦄 API

#30 ✨ feat: stickers/create 페이지 구현
  app/(anon)/stickers/create/page.module.scss
  app/(anon)/stickers/create/page.tsx
  app/api/stickerstyles/route.ts
  application/usecases/stickerStyle/DfStickerStyleListUsecase.ts
  application/usecases/stickerStyle/dto/StickerStyleDto.ts
  components/itemBox/ItemBox.module.scss
  components/rolly/Rolly.module.scss
  components/rolly/Rolly.tsx
  components/rolly/Rolly.type.ts
  components/verticalScrollContainer/VerticalScrollContainer.tsx
  components/verticalScrollContainer/VerticalScrollContinaer.module.scss
  domain/entities/StickerStyle.ts
  domain/entities/StickerTheme.ts
  domain/repositories/StickerStyleRepository.ts
  domain/repositories/StickerThemeRepository.ts
  infrastructure/repositories/SbStickerStyleRepository.ts
  infrastructure/repositories/SbStickerThemeRepository.ts
  package-lock.json
  package.json
Labels: ✨ feature

#31 ✨ feat: 롤리별 스티커 데이터 조회 구현
  app/(anon)/rollies/[id]/page.tsx
  app/api/stickers/route.ts
  app/member/rollies/[id]/page.tsx
  application/usecases/sticker/DfStickersUsecase.ts
  application/usecases/sticker/dto/StickerDto.ts
  components/rolly/Rolly.tsx
  components/rolly/Rolly.type.ts
  domain/entities/Sticker.ts
  domain/repositories/StickerRepository.ts
  infrastructure/repositories/SbStickerRepository.ts
Labels: 🦄 API

#32 🐛 fix: 배포 전 여러 버그 픽스
  app/(anon)/postits/create/page.tsx
  app/(anon)/rollies/[id]/page.tsx
  app/member/rollies/[id]/page.tsx
  app/member/stickers/create/page.module.scss
  app/member/stickers/create/page.tsx
  components/homeButton/HomeButton.module.scss
  components/homeButton/HomeButton.tsx
Labels: 🐛 fix

#34 🐛 fix: 배포 전 여러 버그 픽스
  app/(anon)/rollies/[id]/page.tsx
  app/(anon)/stickers/create/page.module.scss
  app/(anon)/stickers/create/page.tsx
  app/api/rollies/[id]/route.ts
  app/member/rollies/[id]/page.tsx
  app/member/stickers/create/page.module.scss
  app/member/stickers/create/page.tsx
  components/createStickerButton/CreateStickerButton.tsx
  components/imageDownloadButton/ImageDownloadButton.tsx
  components/rolly/Rolly.tsx
  infrastructure/repositories/SbImageRepository.ts
  package-lock.json
  package.json
Labels: 🐛 fix

#35 🐛 fix: 배포 전 여러 버그 픽스
  app/auth/page.tsx
  components/rolly/Rolly.module.scss
Labels: 🐛 fix
